# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, null=True, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.TextField(default='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('courseManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login_reg_app.User')),
            ],
            managers=[
                ('userCourseManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user_courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course_app.UserCourse'),
        ),
    ]
