# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20170228_0556'),
        ('course_app', '0002_auto_20170228_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='user_courses',
            field=models.ManyToManyField(related_name='course', to='login_reg_app.User'),
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
