# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20170228_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_courses',
            field=models.ManyToManyField(related_name='courses', to='login_reg_app.User'),
        ),
    ]
